tensorflow:
  modeldir: "model" # working directory for tensorflow
  host: http://hostName.com:8888 
mongo:
  host: http://hostname.com:8888
  database: cerberServer
  table: messages
queue:
  host: amqp://login:password@host.com:5672/
  topic: picturesQueue
email:
  host: smtp.host.com
  port: 587
  login: login@host.com
  password: password