tensorflow:
  modeldir: "model" # working directory for tensorflow
  host: http://hostName.com:8888 
mongo:
  host: http://hostname.com:8888
  database: cerberServer
  table: messages
queue:
  host: amqp://guest:guest@cerber.cloudapp.net:5672/
  topic: picturesQueue